### ISSUE TITLE
Is this interaction with blockchain only or does work with sawtooth ledger development as well?

### ISSUE THREAD

**Issue by FrankC01** [ozjongwon/clojure-fabric#1]
Excuse my utter degree of ignorance and lack of crisp understanding as I am starting in hyperledger/sawtooth development but would rather do so in Clojure.

Thanks
Frank

**Comment by ozjongwon** [comment]
Fabric and sawtooth are different projects and you need a different clent
SDK - one of
https://github.com/hyperledger/sawtooth-core/tree/master/sdk/

Fabric client is generally the super set of other projects. So conceptually
you can get all the functionality of sawtooth client SDK from my project,
but implementation details may not be compatible.

A short answer is no, a long answer is implementing sawtooth client SDK by
cherry picking from my project is a very simple and mechanical task as far
as I understand.

Hope this helps

Jong-won


On 13 Jan 2018 10:41 pm, "Frank Castellucci" <notifications@github.com>
wrote:

Excuse my utter degree of ignorance and lack of crisp understanding as I am
starting in hyperledger/sawtooth development but would rather do so in
Clojure.

Thanks
Frank

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ozjongwon/clojure-fabric/issues/1>, or mute the thread

**Comment by FrankC01** [comment]
Jong-won

Your response put things into the correct perspective for me. The application is being developed in Python (despite my urging otherwise) but obviously the client can be in any language.

For client development (PoC, etc.) for the application I will be trying out your library and provide any feedback and/or improvements (pull requests) from my experience.

Thanks
